# Generated by Django 4.2.30 on 2026-06-07 02:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StepAction',
            fields=[
                ('action_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=100)),
                ('action_config', models.TextField(blank=True, null=True)),
                ('execution_order', models.IntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'step_action',
                'ordering': ['execution_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowAuditLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('from_status', models.CharField(blank=True, max_length=50, null=True)),
                ('to_status', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workflow_audit_log',
                'ordering': ['-logged_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('workflow_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflow_definition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('instance_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('InProgress', 'In Progress'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('OnHold', 'On Hold')], default='Draft', max_length=50)),
                ('reference_no', models.CharField(max_length=50, unique=True)),
                ('request_data', models.TextField(blank=True, null=True)),
                ('priority', models.SmallIntegerField(default=2)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_instance',
                'ordering': ['-started_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('step_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('step_name', models.CharField(max_length=200)),
                ('step_type', models.CharField(default='Manual', max_length=50)),
                ('step_order', models.IntegerField()),
                ('is_initial', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('sla_hours', models.IntegerField(blank=True, null=True)),
                ('entry_condition', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workflow_step',
                'ordering': ['step_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Delegated', 'Delegated'), ('Overdue', 'Overdue'), ('Skipped', 'Skipped')], default='Pending', max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_task',
                'ordering': ['due_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('transition_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('transition_name', models.CharField(max_length=200)),
                ('trigger_event', models.CharField(max_length=100)),
                ('condition', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workflow_transition',
                'managed': False,
            },
        ),
    ]
