version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: compliance_postgres

    environment:
      POSTGRES_DB: compliance
      POSTGRES_USER: compliance
      POSTGRES_PASSWORD: compliance

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

  redis:
    image: redis:7

    container_name: compliance_redis

    ports:
      - "6379:6379"

  backend:

    build: ./backend

    container_name: compliance_api

    command: >
      sh -c "
      python manage.py migrate &&
      gunicorn config.wsgi:application
      --bind 0.0.0.0:8000
      "

    volumes:
      - ./backend:/app

    ports:
      - "8000:8000"

    depends_on:
      - postgres
      - redis

  celery:

    build: ./backend

    command: celery -A config worker -l info

    volumes:
      - ./backend:/app

    depends_on:
      - redis
      - postgres

  celery-beat:

    build: ./backend

    command: celery -A config beat -l info

    volumes:
      - ./backend:/app

    depends_on:
      - redis
      - postgres

  frontend:

    build: ./frontend

    ports:
      - "3000:80"

volumes:
  postgres_data: