# Generated by Django 4.2.30 on 2026-06-07 02:23

import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notif_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Push', 'Push'), ('Teams', 'Microsoft Teams'), ('Slack', 'Slack')], default='Email', max_length=50)),
                ('subject', models.CharField(blank=True, max_length=500, null=True)),
                ('body', models.TextField()),
                ('is_sent', models.BooleanField(db_index=True, default=False)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.SmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('instance', models.ForeignKey(db_column='instance_id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workflows.workflowinstance')),
                ('user', models.ForeignKey(db_column='user_Id', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-scheduled_at'],
                'managed': False,
            },
        ),
    ]
