# Generated by Django 4.2.30 on 2026-06-07 02:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(default='', max_length=150)),
                ('last_name', models.CharField(default='', max_length=150)),
                ('email', models.CharField(default='', max_length=254)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('table_name', models.CharField(blank=True, max_length=50, null=True)),
                ('record_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=10, null=True)),
                ('old_data', models.TextField(blank=True, null=True)),
                ('new_data', models.TextField(blank=True, null=True)),
                ('changed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('changed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-changed_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('facility_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('activity_status', models.BooleanField(blank=True, null=True)),
                ('active_date', models.DateTimeField(blank=True, null=True)),
                ('deactive_date', models.DateTimeField(blank=True, null=True)),
                ('master_facility_id', models.IntegerField(blank=True, null=True)),
                ('master', models.BooleanField(blank=True, null=True)),
                ('checked', models.BooleanField(blank=True, null=True)),
                ('temp_notes', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('temp_loc', models.IntegerField(blank=True, null=True)),
                ('temp_name', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('last_edit_date', models.DateTimeField(blank=True, null=True)),
                ('last_edit_by', models.IntegerField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacilityLocation',
            fields=[
                ('location_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('xcoordinate', models.FloatField(blank=True, null=True)),
                ('ycoordinate', models.FloatField(blank=True, null=True)),
                ('addressid', models.IntegerField(blank=True, null=True)),
                ('intersectionid', models.IntegerField(blank=True, null=True)),
                ('addressline1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('addressline2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=25, null=True)),
                ('citystatezip', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('stateprovince', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('postalcode', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15, null=True)),
                ('zipplus4', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='zipPlus4', max_length=15, null=True)),
                ('addressnumberprefix', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('addressnumber', models.IntegerField(blank=True, null=True)),
                ('addressnumbersuffix', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('streetnamepremodifier', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('streetnamepredirectional', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('streetnamepretype', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('streetname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('streetnameposttype', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('streetnamepostdirectional', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('streetnamepostmodifier', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('unittype', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('unitidentifier', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('buildingidentifier', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('buildingtype', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('compositeunitidentifier', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('compositeunittype', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('postalplacename', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('country', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('countyname', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('postaldeliveryline', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100, null=True)),
                ('postallastline', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('postaldeliverable', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('postaldeliverynotes', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('source', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('type', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=0, max_digits=18, null=True)),
                ('parsed', models.BooleanField(blank=True, null=True)),
                ('parsedremainder', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=10, null=True)),
                ('easting', models.FloatField(blank=True, null=True)),
                ('northing', models.FloatField(blank=True, null=True)),
                ('coordinatesystem', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('datum', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('comments', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('displayline1', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=80, null=True)),
                ('displayline2', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('displaycitystatezip', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
                ('lasteditdate', models.DateTimeField(blank=True, null=True)),
                ('lasteditby', models.IntegerField(blank=True, null=True)),
                ('creationdate', models.DateTimeField(blank=True, null=True)),
                ('createdby', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'facility_locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('facility_type_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('code', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=5)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'facility_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramDistricts',
            fields=[
                ('program_district_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('district', models.SmallIntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=50, null=True)),
            ],
            options={
                'db_table': 'program_districts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramFacility',
            fields=[
                ('program_facility_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('profile', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=4000)),
                ('tracking_id', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20, null=True)),
                ('risk_assessment', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=5, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('activity_flag', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=1, null=True)),
                ('license_number', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15, null=True)),
                ('license_expire_date', models.DateTimeField(blank=True, null=True)),
                ('last_visit_date', models.DateTimeField(blank=True, null=True)),
                ('next_visit_date', models.DateTimeField(blank=True, null=True)),
                ('facility_phone', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=15, null=True)),
                ('activity_change_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=255, null=True)),
                ('visit_month_seed', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'program_facilities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramFacilityType',
            fields=[
                ('program_facility_type_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('profile_template', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=4000)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=200, null=True)),
            ],
            options={
                'db_table': 'program_facility_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramFacilityTypeActivity',
            fields=[
                ('program_facility_type_activity_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('foapalstring_id', models.CharField(max_length=36)),
                ('description', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'program_facility_type_activities',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Specialtracking',
            fields=[
                ('specialtracking_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('trackingcode', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=20)),
                ('trackingdescription', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', max_length=100)),
            ],
            options={
                'db_table': 'specialtracking',
                'managed': False,
            },
        ),
    ]
