# Generated by Django 6.0.6 on 2026-06-10 16:57

import apps.core.db_fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_programs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserProgramDistrict',
            fields=[
                ('auth_user_program_district_id', models.CharField(default=apps.core.db_fields.new_guid_str, max_length=36, primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_program_districts',
                'managed': False,
            },
        ),
    ]
