# Generated by Django 6.0.6 on 2026-06-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_program_facility_visit_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'managed': True, 'ordering': ['-changed_at']},
        ),
        migrations.AlterModelOptions(
            name='authuser',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'managed': True, 'verbose_name_plural': 'facilities'},
        ),
        migrations.AlterModelOptions(
            name='facilitylocation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='facilitytype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='programdistricts',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='programfacility',
            options={'managed': True, 'verbose_name_plural': 'program facilities'},
        ),
        migrations.AlterModelOptions(
            name='programfacilitytype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='programfacilitytypeactivity',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='specialtracking',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userprogram',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='userprogramdistrict',
            options={'managed': True},
        ),
        migrations.RemoveConstraint(
            model_name='riskassessmentlevel',
            name='unique_risk_code_per_pft',
        ),
        migrations.AlterField(
            model_name='riskassessmentlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='riskassessmentlevel',
            unique_together={('code', 'program_facility_type')},
        ),
    ]
