# Generated by Django 6.0.6 on 2026-06-18 18:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compliance', '0002_add_missing_fks'),
        ('core', '0008_authuser_groups_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FineCase',
            fields=[
                ('fine_case_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('PaymentPlan', 'Payment Plan'), ('Paid', 'Paid'), ('Appealed', 'Appealed'), ('Waived', 'Waived'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('opened_date', models.DateField(default=django.utils.timezone.localdate)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('program_facility', models.ForeignKey(db_column='program_facility_id', on_delete=django.db.models.deletion.PROTECT, related_name='fine_cases', to='core.programfacility')),
            ],
            options={
                'db_table': 'enforcement_fine_cases',
                'ordering': ['-opened_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FineInvoice',
            fields=[
                ('fine_invoice_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('waived_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('PartiallyPaid', 'Partially Paid'), ('Paid', 'Paid'), ('Voided', 'Voided'), ('Waived', 'Waived')], default='Open', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='enforcement.finecase')),
            ],
            options={
                'db_table': 'enforcement_fine_invoices',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='FineAssessment',
            fields=[
                ('fine_assessment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessed_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('waived_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Appealed', 'Appealed'), ('Waived', 'Waived'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fine_tier', models.ForeignKey(blank=True, help_text='The schedule tier that determined the base amount.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='compliance.finetier')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fine_assessments', to='compliance.complianceviolation')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='enforcement.finecase')),
                ('invoice', models.ForeignKey(blank=True, help_text='Populated when the assessment is included on an invoice.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_items', to='enforcement.fineinvoice')),
            ],
            options={
                'db_table': 'enforcement_fine_assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('payment_plan_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_date', models.DateField(default=django.utils.timezone.localdate)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('number_of_installments', models.PositiveIntegerField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('frequency', models.CharField(choices=[('Monthly', 'Monthly'), ('Bimonthly', 'Bimonthly'), ('Quarterly', 'Quarterly'), ('Custom', 'Custom')], max_length=20)),
                ('first_due_date', models.DateField()),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Defaulted', 'Defaulted'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment_plan', to='enforcement.fineinvoice')),
            ],
            options={
                'db_table': 'enforcement_payment_plans',
                'ordering': ['-plan_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentPlanInstallment',
            fields=[
                ('installment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Overdue', 'Overdue'), ('Waived', 'Waived')], default='Pending', max_length=20)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='enforcement.paymentplan')),
            ],
            options={
                'db_table': 'enforcement_payment_plan_installments',
                'ordering': ['installment_number'],
                'unique_together': {('plan', 'installment_number')},
            },
        ),
        migrations.CreateModel(
            name='FinePayment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('Check', 'Check'), ('ACH', 'ACH'), ('CreditCard', 'Credit Card'), ('Cash', 'Cash'), ('Wire', 'Wire'), ('Other', 'Other')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Cleared', 'Cleared'), ('Returned', 'Returned'), ('Voided', 'Voided')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='enforcement.fineinvoice')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('installment', models.ForeignKey(blank=True, help_text='Link to the installment this payment satisfies (if on a plan).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='enforcement.paymentplaninstallment')),
            ],
            options={
                'db_table': 'enforcement_fine_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('receipt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='enforcement.finepayment')),
            ],
            options={
                'db_table': 'enforcement_payment_receipts',
                'ordering': ['-issued_at'],
            },
        ),
    ]
