# Generated by Django 6.0.6 on 2026-06-19 03:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enforcement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FineAppeal',
            fields=[
                ('appeal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appeal_date', models.DateField(default=django.utils.timezone.localdate)),
                ('grounds', models.TextField(help_text='Grounds and reasoning provided by the appellant.')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('UnderReview', 'Under Review'), ('Upheld', 'Upheld'), ('Reduced', 'Reduced'), ('Dismissed', 'Dismissed'), ('Withdrawn', 'Withdrawn')], default='Pending', max_length=20)),
                ('hearing_date', models.DateField(blank=True, null=True)),
                ('decision_notes', models.TextField(blank=True, null=True)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('adjusted_amount', models.DecimalField(blank=True, decimal_places=2, help_text='New assessed amount if the appeal is Reduced. Leave blank for Upheld/Dismissed.', max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appeals', to='enforcement.fineassessment')),
                ('decided_by', models.ForeignKey(blank=True, help_text='Staff member who recorded the appeal decision.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('filed_by', models.ForeignKey(blank=True, help_text='Staff member who recorded/filed the appeal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'enforcement_fine_appeals',
                'ordering': ['-appeal_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FineWaiver',
            fields=[
                ('waiver_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waived_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('authorization_date', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(blank=True, help_text='Set when waiving a specific assessment line.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waivers', to='enforcement.fineassessment')),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, help_text='Set when waiving at the invoice level.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waivers', to='enforcement.fineinvoice')),
            ],
            options={
                'db_table': 'enforcement_fine_waivers',
                'ordering': ['-authorization_date', '-created_at'],
            },
        ),
    ]
