# Generated by Django 6.0.6 on 2026-06-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_add_missing_fks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': True, 'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'managed': True, 'ordering': ['code'], 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='foapalstring',
            options={'managed': True, 'ordering': ['foapal_code']},
        ),
        migrations.AlterModelOptions(
            name='fund',
            options={'managed': True, 'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': True, 'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='org',
            options={'managed': True, 'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'managed': True, 'ordering': ['-transaction_date', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transactionsplit',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
    ]
