# Generated by Django 4.2.30 on 2026-06-07 02:23

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import apps.core.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItemComplianceRules',
            fields=[
                ('checklist_item_compliance_rule_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'checklist_item_compliance_rules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('item_id', apps.core.db_fields.GUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_text', models.CharField(max_length=500)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('response_type', models.CharField(choices=[('YesNo', 'Yes / No'), ('Text', 'Text'), ('Number', 'Number'), ('Date', 'Date'), ('SingleChoice', 'Single Choice'), ('MultiChoice', 'Multi Choice'), ('FileUpload', 'File Upload'), ('Signature', 'Signature')], default='YesNo', max_length=50)),
                ('display_order', models.IntegerField(default=1)),
                ('is_required', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, help_text='Non-empty list of strings for SingleChoice / MultiChoice items.', null=True)),
                ('default_value', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'checklist_item',
                'ordering': ['display_order'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('template_id', apps.core.db_fields.GUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=True, help_text='Required checklists are automatically created when an instance enters the step.')),
                ('blocks_advance', models.BooleanField(default=True, help_text='Prevent advancing the workflow until this checklist is completed or skipped.')),
                ('display_order', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.ForeignKey(blank=True, help_text='Leave blank to attach to all steps of the workflow.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_templates', to='workflows.workflowstep')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='workflows.workflowdefinition')),
            ],
            options={
                'db_table': 'checklist_template',
                'ordering': ['display_order', 'title'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistRun',
            fields=[
                ('run_id', apps.core.db_fields.GUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NotStarted', 'Not Started'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Skipped', 'Skipped')], db_index=True, default='NotStarted', max_length=50)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_items', models.IntegerField(default=0, editable=False)),
                ('total_required', models.IntegerField(default=0, editable=False)),
                ('answered_items', models.IntegerField(default=0, editable=False)),
                ('answered_required', models.IntegerField(default=0, editable=False)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_runs', to='workflows.workflowinstance')),
                ('task', models.ForeignKey(blank=True, db_column='task_Id', help_text='Optional: scope this run to a specific task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_runs', to='workflows.workflowtask')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='checklists.checklisttemplate')),
            ],
            options={
                'db_table': 'checklist_run',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistResponse',
            fields=[
                ('response_id', apps.core.db_fields.GUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('response_value', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='checklists.checklistitem')),
                ('responded_by', models.ForeignKey(db_column='responded_by', on_delete=django.db.models.deletion.PROTECT, related_name='checklist_responses', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='checklists.checklistrun')),
            ],
            options={
                'db_table': 'checklist_response',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checklists.checklisttemplate'),
        ),
        migrations.AddIndex(
            model_name='checklisttemplate',
            index=models.Index(fields=['workflow', 'step'], name='idx_chktmpl_wf_step'),
        ),
        migrations.AddIndex(
            model_name='checklistrun',
            index=models.Index(fields=['instance', 'status'], name='idx_chkrun_inst_status'),
        ),
        migrations.AddIndex(
            model_name='checklistresponse',
            index=models.Index(fields=['run'], name='idx_chkresp_run'),
        ),
        migrations.AlterUniqueTogether(
            name='checklistresponse',
            unique_together={('run', 'item')},
        ),
        migrations.AddIndex(
            model_name='checklistitem',
            index=models.Index(fields=['template', 'display_order'], name='idx_chkitem_tmpl_order'),
        ),
    ]
