# Generated by Django 6.0.6 on 2026-06-19 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0006_checklistitem_example_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'managed': False, 'ordering': ['category', 'display_order']},
        ),
    ]
