# Generated by Django 6.0.6 on 2026-06-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0007_alter_checklistitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklistitemcompliancerules',
            options={'managed': True},
        ),
    ]
