# Generated by Django 4.2.30 on 2026-06-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VWChecklistProgress',
            fields=[
                ('instance_id', models.UUIDField(primary_key=True, serialize=False)),
                ('reference_no', models.CharField(max_length=50)),
                ('checklist_title', models.CharField(db_column='Checklisttitle', max_length=300)),
                ('blocks_advance', models.BooleanField()),
                ('run_status', models.CharField(db_column='Runstatus', max_length=50)),
                ('total_items', models.IntegerField(db_column='TotalItems')),
                ('required_items', models.IntegerField(db_column='RequiredItems')),
                ('answered_items', models.IntegerField(db_column='AnsweredItems')),
                ('answered_required', models.IntegerField(db_column='AnsweredRequired')),
                ('pct_complete', models.DecimalField(db_column='PctComplete', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'VW_ChecklistProgress',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VWInstanceDashboard',
            fields=[
                ('instance_id', models.UUIDField(primary_key=True, serialize=False)),
                ('reference_no', models.CharField(max_length=50)),
                ('workflow_name', models.CharField(db_column='WorkflowName', max_length=200)),
                ('category', models.CharField(db_column='Category', max_length=100, null=True)),
                ('initiated_by', models.CharField(max_length=302)),
                ('current_step', models.CharField(db_column='CurrentStep', max_length=200, null=True)),
                ('status', models.CharField(max_length=50)),
                ('priority', models.SmallIntegerField(db_column='Priority')),
                ('started_at', models.DateTimeField()),
                ('due_date', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('elapsed_hours', models.IntegerField(db_column='ElapsedHours', null=True)),
                ('total_tasks', models.IntegerField(db_column='TotalTasks')),
                ('completed_tasks', models.IntegerField(db_column='CompletedTasks')),
                ('total_checklists', models.IntegerField(db_column='TotalChecklists')),
                ('completed_checklists', models.IntegerField(db_column='CompletedChecklists')),
                ('checklist_pct_done', models.DecimalField(db_column='ChecklistPctDone', decimal_places=1, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'VW_InstanceDashboard',
                'ordering': ['-started_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VWPendingTask',
            fields=[
                ('task_id', models.UUIDField(primary_key=True, serialize=False)),
                ('reference_no', models.CharField(max_length=50)),
                ('workflow_name', models.CharField(db_column='WorkflowName', max_length=200)),
                ('step_name', models.CharField(max_length=200)),
                ('assigned_to', models.CharField(max_length=302)),
                ('assignee_email', models.CharField(db_column='AssigneeEmail', max_length=254)),
                ('status', models.CharField(max_length=50)),
                ('assigned_at', models.DateTimeField()),
                ('due_date', models.DateTimeField(null=True)),
                ('hours_remaining', models.IntegerField(db_column='HoursRemaining', null=True)),
                ('priority', models.SmallIntegerField(db_column='Priority')),
            ],
            options={
                'db_table': 'VW_PendingTasks',
                'ordering': ['due_date'],
                'managed': False,
            },
        ),
    ]
