# Generated by Django 4.2.30 on 2026-06-07 02:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistItemComplianceRule',
            fields=[
                ('checklist_item_compliance_rule_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'checklist_item_compliance_rules',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('compliance_rule_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=25, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'compliance_rules',
                'ordering': ['code'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplianceViolation',
            fields=[
                ('compliance_violation_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('violation_date', models.DateField()),
                ('violation_description', models.TextField(blank=True, null=True)),
                ('detected_by', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'compliance_violations',
                'ordering': ['-violation_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FineSchedule',
            fields=[
                ('fine_schedule_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('schedule_name', models.CharField(max_length=100)),
                ('effective_date', models.DateField()),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fine_schedules',
                'ordering': ['-effective_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FineTier',
            fields=[
                ('fine_tier_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('offense_number', models.IntegerField()),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('days_to_correct', models.IntegerField(blank=True, null=True)),
                ('suspension_required', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'fine_tiers',
                'ordering': ['offense_number'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViolationSeverityLevel',
            fields=[
                ('violation_severity_level_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('rank', models.IntegerField()),
            ],
            options={
                'db_table': 'violationseveritylevels',
                'ordering': ['rank'],
                'managed': False,
            },
        ),
    ]
